[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://rawlight.netlify.app"
  NODE_VERSION = "18"
  NETLIFY = "true"

# Redireciona todas as solicitações para o Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Redirect para páginas de idioma
[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/pt"
  to = "/pt/"
  status = 301

[[redirects]]
  from = "/es"
  to = "/es/"
  status = 301

[[redirects]]
  from = "/de"
  to = "/de/"
  status = 301

[[redirects]]
  from = "/fr"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/it"
  to = "/it/"
  status = 301

[[redirects]]
  from = "/fil"
  to = "/fil/"
  status = 301

# Fallback para todas as rotas
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Configuração de cache para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
